### ISSUE TITLE
1

### ISSUE THREAD

**Issue by inikonorov** [deeplook/freebora#2]

**Comment by deeplook** [comment]
Sorry, I haven't used this in a while, and have just realized that it might not be usable anymore after O'Reilly's move to offer all online content on their Safari platform only, which was about one year ago. I will add a note in the README.

Otherwise, with `python setup.py install` you get a tool named `freebora` that you can get help for with `freebora -h`. I agree the description is lacking, and the CLI sucked (already when it worked), but this was only a little tool meant to be more of a proof of concept rather than a battle-tested thing.
